runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  NODE_ENV: 'prod'
  MONGO_URI: 'mongodb://samucapark3000:Star@9807@ds161410.mlab.com:61410/muse-con'
  TOKEN_SECRET: 'c20171ca-a894-4672-847c-b9bb08b8eac8'
