version: "3.7"
services:
  web:
    restart: always
    build: .
    env_file: .env
    ports:
      - "80:8087"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  db-data:
